app:
    name: shop
    env: local

http:
    host: 0.0.0.0
    port: 8080
    timeout: 5s

postgres:
    host: localhost
    port: 5432
    user: postgres
    password: ""
    dbname: shop_db
    sslmode: disable

redis:
    host: localhost
    port: 6379
    password: ""
    db: 0

jwt:
    # Рекомендуется задавать через переменные окружения: JWT_SECRET, JWT_TTL
    secret: ""
    ttl: 24h

auth:
    # Рекомендуется задавать через переменные окружения:
    # AUTH_BUYER_PASSWORD, AUTH_SELLER_PASSWORD
    buyer_password: ${AUTH_BUYER_PASSWORD}
    seller_password: ${AUTH_SELLER_PASSWORD}

logging:
    level: debug
    port: 514
    host: localhost 



