basePath: /
definitions:
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handler.LoginResponse:
    properties:
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a backend API for Paraklit Shop.
  title: Paraklit Shop API
  version: "1.0"
paths:
  /api/buyer/orders:
    post:
      description: Create a new order based on the user's cart
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      - BearerAuth: []
      summary: Create a new order
      tags:
      - orders
  /auth/login:
    post:
      consumes:
      - application/json
      description: Проверяет учетные данные пользователя и возвращает JWT токен при
        успешной аутентификации.
      parameters:
      - description: Login Request
        in: body
        name: loginRequest
        required: true
        schema:
          properties:
            password:
              type: string
            username:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /cart:
    get:
      consumes:
      - application/json
      description: Возвращает содержимое корзины пользователя
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Просмотр корзины
      tags:
      - cart
  /cart/add/{productId}:
    post:
      consumes:
      - application/json
      description: Добавляет указанный товар в корзину пользователя
      parameters:
      - description: ID товара
        in: path
        name: productId
        required: true
        type: integer
      - description: Количество
        in: path
        name: qty
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Добавить товар в корзину
      tags:
      - cart
  /cart/clear:
    delete:
      consumes:
      - application/json
      description: Удаляет все товары из корзины пользователя
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Очистить корзину
      tags:
      - cart
  /cart/remove/{productId}:
    delete:
      consumes:
      - application/json
      description: Удаляет указанный товар из корзины пользователя
      parameters:
      - description: ID товара
        in: path
        name: productId
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Удалить товар из корзины
      tags:
      - cart
  /health:
    get:
      consumes:
      - application/json
      description: Возвращает статус здоровья сервиса
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Проверка состояния сервиса
      tags:
      - health
  /products:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all products available in the store
      produces:
      - application/json
      responses: {}
      summary: Выводит список всех продуктов
      tags:
      - products
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
